language: ruby
rvm:
  - 2.7.1

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

before_install:
  - rvm @default,@global do gem uninstall bundler -x
  - gem install bundler -v 2.0.1
  - bundle --version
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

script:
  - bundle exec rubocop features

cache:
  bundler: true
